window.CHANAR_DATA = {
  meta:{updated:'2026-09-15',version:'2.1',note:'Base inicial construida con fuentes oficiales provinciales, Turismo Neuquén, registros públicos y directorio local. Los horarios comerciales pueden cambiar; verificar antes de publicar como dato permanente.'},
  place:{
    name:'San Patricio del Chañar',
    province:'Neuquén',department:'Añelo',country:'Argentina',
    access:['Ruta Provincial 7','Ruta Provincial 8'],
    river:'Río Neuquén',
    distanceNeuquen:'aprox. 48 km según fuente oficial provincial de 2013',
    population2022:'10.888 habitantes según resultados del Censo 2022 citados para el municipio',
    area:'7.549 ha según Información Municipal Básica 1999-2000; verificar actualización si se necesita superficie actual',
    founded:'21 de mayo de 1973: creación de la Comisión de Fomento por Decreto Provincial 1339',
    municipalHistory:'1978 municipio de tercera categoría; 1987 segunda categoría; 2003 primera categoría',
    namesake:'San Patricio se vincula con Campo Filone, Italia, de donde procedía la familia Gasparri. Chañar es el nombre histórico del paraje asociado al chical/chañar.',
    sources:[
      {label:'Neuquén Informa — historia local',url:'https://www.neuqueninforma.gob.ar/amp/noticias/2013/05/17/29151-ana-pechen-preside-la-ceremonia-aniversario-de-san-patricio-del-chanar'},
      {label:'Estadística Neuquén — información municipal',url:'https://www.estadisticaneuquen.gob.ar/static/archivos/Publicaciones/InfMunBasica/Basica99-00/CARTOGRAFIA/San%20Patricio.PDF'}
    ]
  },
  sectors:[
    {icon:'🍎',title:'Fruticultura',text:'El oasis de riego sostiene producción de peras, manzanas y frutas de carozo. Una fuente oficial provincial informó que el ejido concentraba más del 40% de la superficie frutícola provincial y que alrededor del 60% de la producción mencionada se destinaba a exportación.',source:'Neuquén Informa 2013',url:'https://www.neuqueninforma.gob.ar/amp/noticias/2013/05/17/29151-ana-pechen-preside-la-ceremonia-aniversario-de-san-patricio-del-chanar'},
    {icon:'🍷',title:'Vitivinicultura',text:'San Patricio del Chañar es uno de los principales polos vitivinícolas de Neuquén. Turismo Neuquén destaca bodegas modernas, visitas, degustaciones y gastronomía.',source:'Turismo Neuquén',url:'https://turismo.neuquen.gob.ar/que-hacer-donde-vive-el-vino/'},
    {icon:'🌱',title:'Agroturismo y producción local',text:'La oferta turística se está ampliando hacia experiencias rurales, producción, gastronomía, emprendimientos y recorridos por chacras.',source:'Neuquén Informa 2026',url:'https://www.neuqueninforma.gob.ar/noticias/2026/07/10/260413-san-patricio-del-chanar-realizara-la-primera-feria-regional-de-turismo-sabores-y-amigos'},
    {icon:'⛽',title:'Entorno Vaca Muerta',text:'La localidad forma parte del corredor de actividad de Vaca Muerta y su crecimiento está impactando en demanda de salud, educación, infraestructura, servicios y movilidad.',source:'Ministerio de Salud / Neuquén Informa',url:'https://salud.neuquen.gob.ar/se-fortalece-el-sistema-de-salud-en-la-region-vaca-muerta/'},
    {icon:'🎭',title:'Cultura y comunidad',text:'La Fiesta Provincial del Pelón reúne producción, trabajador rural, música, danzas, destrezas criollas, gastronomía, artesanos y emprendedores.',source:'Neuquén Informa 2026',url:'https://www.neuqueninforma.gob.ar/noticias/2026/02/10/255111-san-patricio-del-chanar-se-prepara-para-la-fiesta-del-pelon'},
    {icon:'🏞️',title:'Río y recreación',text:'La localidad cuenta con infraestructura recreativa junto al río Neuquén, incluyendo balneario y camping municipal.',source:'Neuquén Informa 2025-2026',url:'https://www.neuqueninforma.gob.ar/noticias/2025/01/13/247652-habilitaron-camping-en-san-patricio-del-chanar'}
  ],
  places:[
    {name:'Hospital San Patricio del Chañar “Dra. Alicia Cruz”',category:'Salud',icon:'🏥',description:'Hospital público local. En 2025 la Provincia informó que era el único prestador con internación de la zona y que entre 70% y 72% de la población utilizaba el sistema público.',phone:'0299 4855084',source:'Ministerio de Salud del Neuquén',url:'https://salud.neuquen.gob.ar/lugar/hospital-san-patricio-del-chanar-dra-alicia-cruz/'},
    {name:'Balneario y Camping Municipal',category:'Turismo',icon:'🏖️',description:'Espacio recreativo sobre el río Neuquén. La habilitación informada en 2025 incluyó más de ocho hectáreas, balneario, piscinas, canchas, sanitarios, parrillas, picnic y 60 unidades de acampe con capacidad informada de 250 personas.',source:'Neuquén Informa',url:'https://www.neuqueninforma.gob.ar/noticias/2025/01/13/247652-habilitaron-camping-en-san-patricio-del-chanar'},
    {name:'Bodega Del Fin del Mundo',category:'Turismo / Bodegas',icon:'🍷',description:'Primera bodega moderna de San Patricio del Chañar, con plantaciones de vid desde 1999. Turismo Neuquén informa visitas a sala de barricas, pasarelas y viñedos.',address:'Chacra 77 / Ruta Provincial 8 km 9',phone:'0299 5809085',source:'Turismo Neuquén',url:'https://turismo.neuquen.gob.ar/alojamientos/bodega-del-fin-del-mundo/'},
    {name:'Bodega Malma',category:'Turismo / Bodegas',icon:'🍷',description:'Bodega ubicada en Ruta Provincial 7 y calle 15; Turismo Neuquén la presenta como parte de la ruta del vino local y destaca su restaurante.',address:'Ruta Provincial 7 y calle 15',phone:'0299 5362700',source:'Turismo Neuquén / directorio local',url:'https://turismo.neuquen.gob.ar/que-hacer-donde-vive-el-vino/'},
    {name:'Bodega Familia Schroeder',category:'Turismo / Bodegas',icon:'🍷',description:'Bodega de arquitectura integrada al terreno. Turismo Neuquén destaca visitas, plantaciones, hallazgo paleontológico durante la construcción y restaurante gourmet.',address:'Calle 7 Norte / Picada 7',phone:'0299 4548920',source:'Turismo Neuquén / directorio local',url:'https://turismo.neuquen.gob.ar/que-hacer-donde-vive-el-vino/'},
    {name:'Bodega Secreto Patagónico',category:'Turismo / Bodegas',icon:'🍷',description:'Bodega que trabaja con selección de viñedos individuales y partidas de alta gama. Turismo Neuquén informa visitas y degustaciones con reserva previa.',address:'Ruta Provincial 7, Picada 4 y media',phone:'011 4813 7409',source:'Turismo Neuquén / directorio local',url:'https://turismo.neuquen.gob.ar/que-hacer-donde-vive-el-vino/'},
    {name:'Bodega Patritti',category:'Turismo / Bodegas',icon:'🍷',description:'Bodega de arquitectura característica, vinculada al paisaje productivo neuquino. Turismo Neuquén la incluye en la oferta enoturística de la región.',address:'Picada 1 s/n',phone:'0299 5118841',source:'Turismo Neuquén / directorio local',url:'https://turismo.neuquen.gob.ar/que-hacer-donde-vive-el-vino/'},
    {name:'Bodega urbana El Chical',category:'Turismo / Cultura / Bodega',icon:'🍷',description:'Bodega boutique inaugurada en 2026 que comercializa vinos de elaboración propia y funciona también como espacio cultural y atractivo turístico.',source:'Neuquén Informa 2026',url:'https://www.neuqueninforma.gob.ar/noticias/2026/04/03/255930-el-chical-se-suma-a-la-oferta-vitivinicola-de-san-patricio-del-chanar'},
    {name:'Hostería El Chañar',category:'Alojamiento',icon:'🛏️',description:'Hostería/posada en Barrio Jardín.',address:'Araucaria 565, Barrio Jardín',phone:'0299 5286731',source:'Turismo Neuquén',url:'https://turismo.neuquen.gob.ar/alojamientos/el-chanar-cuit-n-27-24388984-2/'},
    {name:'Hotel Don Pedro',category:'Alojamiento',icon:'🛏️',description:'Alojamiento local.',address:'Complejo Chocón, manzana L lote 1J',phone:'0299 5746863',source:'Directorio local',url:'https://www.google.com/maps/search/?api=1&query=Hotel+Don+Pedro+San+Patricio+del+Chañar'},
    {name:'Complejo Ruca-Laf',category:'Alojamiento',icon:'🛏️',description:'Complejo de alojamiento en Barrio Jardín.',address:'Araucaria 665, Barrio Jardín',source:'Directorio local',url:'https://www.google.com/maps/search/?api=1&query=Complejo+Ruca-Laf+San+Patricio+del+Chañar'},
    {name:'Complejo Uno Chañar',category:'Alojamiento',icon:'🛏️',description:'Complejo de apartamentos.',address:'Manzana XL, entre Cerda y Av. Malvinas Argentinas',phone:'011 65932796',source:'Directorio local',url:'https://www.google.com/maps/search/?api=1&query=Complejo+Uno+Chañar'},
    {name:'Autoservicio MATY',category:'Comercios',icon:'🛒',description:'Supermercado/autoservicio local.',address:'Calle 121',phone:'0299 4657624',source:'Directorio local',url:'https://www.google.com/maps/search/?api=1&query=Autoservicio+MATY+San+Patricio+del+Chañar'},
    {name:'Pato Lucas',category:'Comercios',icon:'🛒',description:'Supermercado local.',address:'Ex Calle 116 D7 Lote 13',phone:'0299 5240947',source:'Directorio local',url:'https://www.google.com/maps/search/?api=1&query=Pato+Lucas+San+Patricio+del+Chañar'},
    {name:'Chañar Hogar',category:'Comercios',icon:'🏠',description:'Comercio de artículos para el hogar.',address:'Complejo El Chocón y Av. Gasparri Sur',phone:'0299 6111596',source:'Directorio local',url:'https://www.google.com/maps/search/?api=1&query=Chañar+Hogar'},
    {name:'Casa Gonzalez - Repuestos para Autos y Ferretería',category:'Servicios / Automotor',icon:'🔧',description:'Repuestos automotor y ferretería.',address:'Complejo El Chocón 675',phone:'0299 5048585',source:'Directorio local',url:'https://www.google.com/maps/search/?api=1&query=Casa+Gonzalez+San+Patricio+del+Chañar'},
    {name:'Casa Gonzalez Repuestos Automotor y Ferretería',category:'Servicios / Automotor',icon:'🔧',description:'Repuestos automotor y ferretería.',address:'Arroyo Covunco 166',phone:'0299 6725959',source:'Directorio local',url:'https://www.google.com/maps/search/?api=1&query=Casa+Gonzalez+Repuestos+San+Patricio+del+Chañar'},
    {name:'Gm Casa de Repuestos y Servicios Mecánicos',category:'Servicios / Automotor',icon:'🔧',description:'Repuestos y servicios mecánicos.',address:'Cerro Waile, manzana 46G lote 7',phone:'0299 5498275',source:'Directorio local',url:'https://www.google.com/maps/search/?api=1&query=Gm+casa+de+repuestos+San+Patricio+del+Chañar'},
    {name:'Corralón Pitty',category:'Construcción',icon:'🧱',description:'Proveedor de materiales de construcción.',address:'Río Neuquén Mza G2 lotes 11 y 12',phone:'0299 4855419',source:'Directorio local',url:'https://www.google.com/maps/search/?api=1&query=Corralon+Pitty+San+Patricio+del+Chañar'},
    {name:'El Punto Gráfica',category:'Servicios',icon:'🖨️',description:'Imprenta y gráfica.',address:'Complejo El Chocón 800',phone:'0299 5954445',source:'Directorio local',url:'https://www.google.com/maps/search/?api=1&query=El+Punto+Gráfica+San+Patricio+del+Chañar'},
    {name:'Aldana Novedades',category:'Comercios',icon:'🛍️',description:'Tienda de artículos para el hogar.',address:'Quili Malal 8',source:'Directorio local',url:'https://www.google.com/maps/search/?api=1&query=Aldana+Novedades+San+Patricio+del+Chañar'},
    {name:'Procars Chañar',category:'Comercios / Automotor',icon:'🚗',description:'Centro comercial y servicios.',address:'Milum 3',phone:'0299 4516577',source:'Directorio local',url:'https://www.google.com/maps/search/?api=1&query=Procars+Chañar'},
    {name:'MC Calidad SA — sucursal Chañar',category:'Comercios',icon:'🏪',description:'Comercio local.',address:'Complejo El Chocón 6',phone:'0299 5045170',source:'Directorio local',url:'https://www.google.com/maps/search/?api=1&query=MC+Calidad+San+Patricio+del+Chañar'},
    {name:'San Antonio',category:'Comercios / Gastronomía',icon:'🍽️',description:'Comercio/gastronomía local.',address:'Calle Curi Leuvu, C. 122',source:'Directorio local',url:'https://www.google.com/maps/search/?api=1&query=San+Antonio+Curi+Leuvu+San+Patricio+del+Chañar'}
  ],
  education:[
    {name:'EPET N° 26',type:'Educación técnica',text:'Creada en 2022. En junio de 2026 tenía 262 estudiantes. El nuevo edificio proyectado contempla capacidad para 800 estudiantes, talleres y posibilidad de ampliar orientaciones; la obra tiene fecha prevista de finalización en noviembre de 2026.',source:'Neuquén Informa',url:'https://www.neuqueninforma.gob.ar/noticias/2026/06/27/259822-figueroa-visito-junto-a-los-estudiantes-de-la-epet-n-26-la-obra-del-nuevo-edificio-escolar'},
    {name:'Escuela Primaria N° 364',type:'Educación primaria',text:'Nuevo edificio inaugurado en marzo de 2026. Superficie cubierta informada: 1.563 m²; matrícula informada: 222 estudiantes.',source:'Neuquén Informa',url:'https://www.neuqueninforma.gob.ar/noticias/2026/03/06/255471-se-inauguro-el-nuevo-edificio-de-la-escuela-n-364-de-san-patricio-del-chanar'},
    {name:'EPEA N° 3',type:'Educación agropecuaria',text:'Institución educativa vinculada a la formación agropecuaria y a la identidad productiva local. Participó en actividades de promoción del agroturismo y producción local.',source:'Neuquén Informa',url:'https://www.neuqueninforma.gob.ar/noticias/2026/07/10/260413-san-patricio-del-chanar-realizara-la-primera-feria-regional-de-turismo-sabores-y-amigos'},
    {name:'Centro de Formación Profesional Agropecuaria N° 2',type:'Formación profesional',text:'Institución vinculada a formación y proyectos productivos; participó junto a EPEA 3 en la Feria Regional de Turismo 2026.',source:'Neuquén Informa',url:'https://www.neuqueninforma.gob.ar/noticias/2026/07/10/260413-san-patricio-del-chanar-realizara-la-primera-feria-regional-de-turismo-sabores-y-amigos'}
  ],
  infrastructure:[
    {title:'Centro de Día de Salud Mental',status:'EN OBRA',text:'Comenzó en julio de 2026. Superficie total prevista: 75 m², con SUM de 45 m², baño accesible y recepción. Plazo informado: 180 días corridos.',url:'https://www.neuqueninforma.gob.ar/noticias/2026/07/20/260695-comenzo-la-obra-del-centro-de-dia-en-san-patricio-del-chanar'},
    {title:'Centro Deportivo Comunitario',status:'LICITACIÓN',text:'Proyecto de 1.500 m² cubiertos, SUM, salón flexible, cocina, sanitarios, gradas retráctiles para 400 personas, playones, juegos, estacionamientos y espacios comunitarios. Presupuesto oficial informado en agosto de 2026: $4.681.507.895.',url:'https://www.neuqueninforma.gob.ar/noticias/2026/08/02/261335-la-provincia-construira-un-nuevo-centro-deportivo-comunitario-en-san-patricio-del-chanar'},
    {title:'Red de gas para 347 lotes',status:'FINANCIAMIENTO',text:'Aporte reintegrable provincial destinado a ejecutar la red de gas para 347 lotes.',url:'https://www.neuqueninforma.gob.ar/noticias/2026/06/25/259663-la-provincia-financiara-la-red-de-gas-para-347-lotes-en-san-patricio-del-chanar'},
    {title:'Energía para Costa Verde — Picada III',status:'FINANCIAMIENTO',text:'Aporte provincial informado en abril de 2026 para materiales de electrificación del barrio Costa Verde en Picada III.',url:'https://www.neuqueninforma.gob.ar/noticias/2026/04/28/256890-la-provincia-financiara-obras-de-energia-y-gas-en-san-patricio-del-chanar'},
    {title:'EPET 26 — nuevo edificio',status:'EN OBRA',text:'Edificio proyectado de 4.940 m² cubiertos sobre predio de 13.900 m², con aulas, laboratorio, biblioteca multimedia, SUM y 19 talleres.',url:'https://www.neuqueninforma.gob.ar/noticias/2025/12/22/254040-preven-que-este-listo-a-fines-de-2026-el-edificio-de-la-epet-29-de-centenario'}
  ],
  events:[
    {date:'2026-02-14/16',title:'36ª Fiesta Provincial del Pelón',text:'Fiesta productiva y cultural con homenaje al trabajador rural, música, danzas, destrezas criollas, gastronomía, artesanos y emprendedores.',url:'https://www.neuqueninforma.gob.ar/noticias/2026/02/10/255111-san-patricio-del-chanar-se-prepara-para-la-fiesta-del-pelon'},
    {date:'2026-07-12',title:'1ª Feria Regional de Turismo “Sabores y Amigos”',text:'Feria con turismo, gastronomía, vinos, producción local, artesanos, emprendedores y mini tour “Explorá Chañar”.',url:'https://www.neuqueninforma.gob.ar/noticias/2026/07/10/260413-san-patricio-del-chanar-realizara-la-primera-feria-regional-de-turismo-sabores-y-amigos'},
    {date:'2026-07-25/26',title:'Huellas con Ritmo',text:'Programa provincial con actividades recreativas, bienestar, senderismo, expresión corporal e información sobre derechos.',url:'https://www.neuqueninforma.gob.ar/noticias/2026/07/22/260788-huellas-con-ritmo-llega-a-san-patricio-del-chanar-para-fortalecer-el-bienestar-y-promover-derechos'}
  ],
  emergency:[
    {name:'Emergencias',number:'107',source:'Ministerio de Salud del Neuquén'},
    {name:'Defensa Civil',number:'103',source:'Ministerio de Salud del Neuquén'},
    {name:'Maltrato infantil',number:'102',source:'Ministerio de Salud del Neuquén'},
    {name:'Víctimas de violencia',number:'148',source:'Ministerio de Salud del Neuquén'},
    {name:'Hospital San Patricio del Chañar',number:'0299 4855084',source:'Ministerio de Salud del Neuquén'}
  ]
};
