window.CHANAR_GEO = {
  schemaVersion: "1.0",
  updated: "2026-09-15",
  attribution: "Chañar HUB · Ocarina Producciones",
  categories: ["Salud","Educación","Comercio","Turismo","Deporte","Instituciones","Historia","Producción"],
  places: [
    {id:"mun-spc",name:"Municipalidad de San Patricio del Chañar",category:"Instituciones",subcategory:"Gobierno local",lat:-38.62619,lon:-68.29793,status:"verified",confidence:"high",source:"OpenStreetMap / Mapcarta",sourceUrl:"https://mapcarta.com/es/W218470639",verifiedAt:"2026-09-15",description:"Sede municipal de San Patricio del Chañar."},
    {id:"hospital-spc",name:"Hospital de San Patricio del Chañar",category:"Salud",subcategory:"Hospital",lat:-38.62957,lon:-68.29623,status:"verified",confidence:"high",source:"Cartografía pública / búsqueda local",sourceUrl:"https://www.google.com/maps/search/?api=1&query=Hospital+de+San+Patricio+del+Chañar",verifiedAt:"2026-09-15",description:"Establecimiento sanitario local."},
    {id:"plaza-ninos",name:"Plaza Derechos de los Niños",category:"Instituciones",subcategory:"Espacio público",status:"pending",confidence:"medium",source:"Directorio cartográfico local",sourceUrl:"https://www.google.com/maps/search/?api=1&query=Plaza+Derechos+de+los+Niños+San+Patricio+del+Chañar",verifiedAt:"2026-09-15",description:"Punto incorporado al inventario; coordenadas pendientes de verificación independiente."},
    {id:"correo",name:"Correo Argentino",category:"Instituciones",subcategory:"Servicio público",status:"pending",confidence:"medium",source:"Directorio cartográfico local",sourceUrl:"https://www.google.com/maps/search/?api=1&query=Correo+Argentino+San+Patricio+del+Chañar",verifiedAt:"2026-09-15",description:"Ubicación pendiente de coordenadas verificadas."},
    {id:"epet26",name:"EPET N°26",category:"Educación",subcategory:"Secundaria técnica",status:"pending",confidence:"medium",source:"Mapa educativo / directorio cartográfico",sourceUrl:"https://www.google.com/maps/search/?api=1&query=EPET+26+San+Patricio+del+Chañar",verifiedAt:"2026-09-15",description:"Establecimiento educativo; coordenadas pendientes de verificación independiente."},
    {id:"esc273",name:"Escuela Primaria 273 Julio Sang",category:"Educación",subcategory:"Primaria",status:"pending",confidence:"medium",source:"Mapa educativo / directorio cartográfico",sourceUrl:"https://www.google.com/maps/search/?api=1&query=Escuela+Primaria+273+Julio+Sang+San+Patricio+del+Chañar",verifiedAt:"2026-09-15",description:"Establecimiento educativo; coordenadas pendientes de verificación independiente."},
    {id:"emeta",name:"EMETA",category:"Educación",subcategory:"Formación agropecuaria",status:"pending",confidence:"medium",source:"Mapa educativo / directorio cartográfico",sourceUrl:"https://www.google.com/maps/search/?api=1&query=EMETA+San+Patricio+del+Chañar",verifiedAt:"2026-09-15",description:"Institución educativa; coordenadas pendientes de verificación independiente."},
    {id:"club-san-patricio",name:"Club San Patricio del Chañar",category:"Deporte",subcategory:"Club",status:"pending",confidence:"medium",source:"Información pública provincial / directorio cartográfico",sourceUrl:"https://www.google.com/maps/search/?api=1&query=Club+San+Patricio+del+Chañar+Neuquén",verifiedAt:"2026-09-15",description:"Club deportivo local; ubicación exacta pendiente de verificación."},
    {id:"polideportivo",name:"Polideportivo Municipal Ingeniero Tulio Ferraresso",category:"Deporte",subcategory:"Polideportivo",status:"pending",confidence:"medium",source:"Directorio cartográfico local",sourceUrl:"https://www.google.com/maps/search/?api=1&query=Polideportivo+Municipal+Ingeniero+Tulio+Ferraresso+San+Patricio+del+Chañar",verifiedAt:"2026-09-15",description:"Equipamiento deportivo municipal; coordenadas pendientes de verificación."},
    {id:"balneario",name:"Balneario Municipal",category:"Turismo",subcategory:"Recreación",status:"pending",confidence:"medium",source:"Directorio cartográfico local",sourceUrl:"https://www.google.com/maps/search/?api=1&query=Balneario+Municipal+San+Patricio+del+Chañar",verifiedAt:"2026-09-15",description:"Espacio recreativo local; coordenadas pendientes de verificación."},
    {id:"biblioteca",name:"Biblioteca Popular San Patricio del Chañar",category:"Instituciones",subcategory:"Cultura",status:"pending",confidence:"medium",source:"Directorio empresarial/local",sourceUrl:"https://www.google.com/maps/search/?api=1&query=Biblioteca+Popular+San+Patricio+del+Chañar",verifiedAt:"2026-09-15",description:"Biblioteca popular local; ubicación pendiente de verificación independiente."},
    {id:"corralon-pitty",name:"Corralón Pitty",category:"Comercio",subcategory:"Materiales / ferretería",status:"pending",confidence:"medium",source:"Directorio empresarial local",sourceUrl:"https://www.google.com/maps/search/?api=1&query=Corralon+Pitty+San+Patricio+del+Chañar",verifiedAt:"2026-09-15",description:"Comercio local; la ficha cartográfica se utilizará como referencia y no como validación permanente."},
    {id:"cementerio",name:"Cementerio de San Patricio del Chañar",category:"Historia",subcategory:"Patrimonio / memoria",status:"pending",confidence:"medium",source:"Directorio cartográfico local",sourceUrl:"https://www.google.com/maps/search/?api=1&query=Cementerio+San+Patricio+del+Chañar",verifiedAt:"2026-09-15",description:"Punto territorial de memoria; coordenadas pendientes de verificación independiente."}
  ]
};
